# Generated by Django 6.1.1 on 2026-09-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('service', models.CharField(choices=[('Basic Cleaning', 'Basic Cleaning'), ('Interior Cleaning', 'Interior Cleaning'), ('Premium Cleaning', 'Premium Cleaning')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
